### ISSUE TITLE
Vitebook Feedback

### ISSUE THREAD

**Issue by mihar-22** [vitebook/vitebook#36]
Vitebook is slowly growing, but I'm left wondering what features are missing for it to be a truly suitable alternative to Storybook. How does it feel for most of you today? I can come up with stuff but I'd rather hear from all of you! I'm opening this issue for everyone to chime in, and let me know what you'd love to see. Not promising we'll implement everything, but it'll be great to hear more thoughts.

I do want to stress that Vitebook is an _alternative_ to Storybook, please don't misinterpret 'alternative' for 'clone'. Let's try to learn from Storybook and do things in a different way. Sometimes you still might reach for Storybook, but the times where you have different requirements which may be simplicity, speed, and whatever else, Vitebook can be there for you.

Feel free to leave your feedback, thoughts, suggestions, and ideas down below👇 

💭  Maybe we should create a Discord channel or open up GitHub discussions?

**Comment by jacobbowdoin** [comment]
- A **resizable sidebar** using https://github.com/sveltejs/svelte-repl/blob/master/src/SplitPane.svelte as seen in action at https://svelte.dev/repl and https://sveed.dev/tbepqyr4fEe2uTfhXmot - I made a typescript version of it here if you care: https://github.com/jacobbowdoin/svelte-pieces/blob/main/src/lib/ui/SplitPane.svelte - this makes it easy to check out how a component responds to different width constraints. Lots of mocking tools have set sizes which are great but I like even better the ability to quickly drag to any size and I just add a width counter in the upper right like so:
![image](https://user-images.githubusercontent.com/7559478/153547346-4a636765-824c-4397-b20e-5080f55410d8.png)

- Nice to have: **Overview pages** that allow viewers to dive into a particular variant and then easily pop back out as seen in https://svench-docs.vercel.app/_/Usage/knobs and https://github.com/rixo/svench/blob/main/packages/docs/src/03-Usage.svench/20-knobs.md - in this page I can read about knob, easily jump into a particular View/Variant, try it out (using controls/addons) and then pop back out to keep reading. I know Storybook doesn't have this either, but I've found it to be really great. It doesn't look like a trivial task and is more of a workbench feature than documentation so maybe it's out of scope because of the complexity. The way that Vitebook implements addons makes this sort of thing difficult but I did want to put it out there as an valuable concept to keep in view.

Yes, Github discussions are great for this sort of thing with the nested replies, and no I think Discord will cut a lot of people out of seeing the discussion.

**Comment by accuser** [comment]
Having integrated Storybook into a SvelteKit project over the weekend, I was impressed until I started to modify my components. The speed of the round-trip development that I have experienced with SvelteKit has spoilt me, so I was pleasantly surprised when I picked up Vitebook this morning. I replaced Storybook in my project, and added Vitebook to three other projects today - complete with full integration with the existing SvelteKit: I've kept my components under `src/lib` and organised the stories in `src/stories`, which means `svelte-kit package` does something really useful out of the box (I'm using this for a design system package). I'm thoroughly impressed - thank you.

- portal sizing is definitely required. I've got a simple breakpoint component that I float over the body during development, but to be able to switch between mobile / desktop and other pre-defined / user-defined breakpoints would be really useful.
- the controls panel add-on is useful, but I'd like to be able to display it at the bottom of the page rather than on the right-hand side. I like to be able to group the inputs in the panel too, so that I can organise the inputs. I know I can add arbitrary html markup in the add-on, but having a HOC as part of the add-on would make this a more consistent experience.
- variants listed a children of the component (as Storybook) would be useful. The variant drop-down works, but it is not intuitive.
- some naming / structure / organisation, rather than relying on folders.

**Comment by jorrete** [comment]
Hi,
Is there any way to define story files for WebComponents without any framework? A kind of vanilla JavaScript platform?
I have some WebComponents build without any framework (Lit, Polymer) and I would like to integrate them.

**Comment by wildwind123** [comment]
Hello, i am new user for vue, vite.
I tried use storybook, but it requires more knowledge. In vitebook requires knowledge of vue and vite. And i chosen vitebook. Very helpful application. Thank you.

**Comment by jorrete** [comment]
Thanks @mihar-22,
That's enough for my use. I want to put everything in web components and leave orchestration to the framework (probably preact).
More feedback:
I don't know the rest of vite framework plugins, but preact one accepts include and exclude file filters. Playing with that, I think it would be possible to have a Vitebook with different frameworks. Still you have to choose the framework you want to define the stories, but you could have components in different frameworks, which I think i'ts pretty cool. Think of migrating from react 16 to react 17 side by side, that would be helpful for a team. This scenario,  can't be achieved with Storybook elegantly. I think you can connect several projects with a kind of proxy storybook.
Good job.

**Comment by j-o-sh** [comment]
Hi @mihar-22 

Chiming in with the frameworkless/custom-element use case:  I am pretty sure I simply overlooked something in the docs but I am having a hard time, simly integrating my custom elements in a markdown file that is served with vitebook.

My naive approach was that i have a `README.md` file in the same folder as the `my-awsomeelement.js` source file and I tried to import the js file simply in the markdown header:

```markdown
---
title: Awesome Element
head:
  - - script
    - type: module
      src: ./my-awesome-element.js
---

# The element

<my-awesome-element></my-awesome-element>
```

Unfortunatelly that doesn't work, since no simple `.js` files will get served via the default config **but I also couldn't find any hint in the docs as to how to make that possible**.

Any ideas?

**Comment by mihar-22** [comment]
Hey @rottmann, happy to open up GitHub Discussions to help people collab/contribute if that would help. Unfortunately my plate is really full right now so I sadly can't help out too much 😞

**Comment by mihar-22** [comment]
GitHub Discussions is now open: https://github.com/vitebook/vitebook/discussions

Feel free to create a discussion for your ideas, suggestions, feedback and anything else in there 😄

**Comment by bartenra** [comment]
The link to missing features in the README is missing. :stuck_out_tongue:

**Comment by mihar-22** [comment]
--> https://github.com/vitebook/vitebook/discussions/99
